version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
    - ./public:/code
    - ./Configuration/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
  db:
    image: mariadb:latest
    env_file:
    - ./.env
    ports:
    - "8001:5432"
    volumes:
    - run:/var/run/mysqld

    # Use tmpfs for file storage
    - db:/var/lib/mysql
  php:
    build: ./Configuration/
    volumes:
    - ./public:/code
    - ./Configuration/php.conf:/usr/local/etc/php-fpm.d/zz-custom.conf

networks:
  default:
    driver: bridge

volumes:
  db:
    driver_opts:
      type: tmpfs
      device: tmpfs
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
