version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
    - ./public:/code
    - typo3temp:/code/typo3temp
    - ../:/code/typo3conf/ext/wizard_crpagetree
    - ./Configuration/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
  db:
    image: percona:latest
    env_file:
    - ./.env
    ports:
    - "8001:5432"
    volumes:
    - run:/var/run/mysqld

    # Initialize database
    - ./Configuration:/docker-entrypoint-initdb.d/

    # Use tmpfs for file storage
    #- db:/var/lib/mysql

    # Copy custom configuration
    - ./Configuration/mysql.cnf:/etc/mysql/zzz-custom.cnf
  php:
    build: ./Configuration/
    volumes:
    - ./public:/code
    - typo3temp:/code/typo3temp
    - ../:/code/typo3conf/ext/wizard_crpagetree

    # Copy custom fpm configuration
    - ./Configuration/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf

    # Copy custom ini configuration
    - ./Configuration/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini

networks:
  default:
    driver: bridge

volumes:
  db:
    driver_opts:
      type: tmpfs
      device: tmpfs
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  typo3temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
