version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
    - ../:/code
    - typo3tempRamdisk:/code/typo3temp
    - ./Configuration/web/nginx.conf:/etc/nginx/conf.d/default.conf
    expose: [80]
  db:
    image: percona:latest
    env_file:
    - ./.env
    volumes:
    - ./Configuration/db:/docker-entrypoint-initdb.d/
    - dbRamdisk:/var/lib/mysql
    - ./Configuration/db/mysql.cnf:/etc/mysql/zzz-custom.cnf
  php:
    build: ./Configuration/php/
    volumes:
    - ../:/code
    - typo3tempRamdisk:/code/typo3temp
    - ./Configuration/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf
    - ./Configuration/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
  hostmap:
    image: dvdarias/docker-hoster
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/hosts:/tmp/hosts

volumes:
  dbRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
  typo3tempRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs